
---
repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        name: CMake Format
        entry: cmake-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: fprettify
        name: fprettify
        entry: fprettify --silent
        language: system
        types: [file]
        files: '\.(f|F|f90|F90)$'
