name = "template"
version = "0.1.0"
license = "MIT"
author = "JorgeG94"
maintainer = "jorgegalvez1694@gmail.com"
copyright = "Copyright 2024, JorgeG94"
[preprocess]
[preprocess.cpp]
suffixes = ["F90", "f90"]
[library]
source-dir = "src"
[build]
auto-executables = true
auto-tests = false
#auto-examples = true
module-naming = false
[[test]]
name = "sample"
source-dir = "test"
main = "main_tests.f90"
[install]
library = true

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"

[dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"

[extra.fortitude.check]
select = ["C", "E", "S"]
ignore = ["C003"]
line-length = 132
per-file-ignores = { "pic_blas_interfaces.F90" = ["C071"] }
