
name: Setup Fortran Conda CI/CD
#credit: https://github.com/gha3mi/setup-fortran-conda/tree/main
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master]

permissions:
  contents: write
  pull-requests: write

jobs:

  # Run FPM tests (debug + release) on all OS/compiler combinations
  test_fpm:
    name: ${{ matrix.os }}_${{ matrix.compiler }}_fpm
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gfortran, ifx, lfortran, flang-new, nvfortran]
        include:
          - os: ubuntu-latest
            extra-packages: ""
          - os: windows-latest
            extra-packages: ""
          - os: macos-latest
            extra-packages: ""
        exclude:
          - os: macos-latest
            compiler: flang-new
          - os: macos-latest
            compiler: ifx
          - os: macos-latest
            compiler: nvfortran
          - os: windows-latest
            compiler: nvfortran

    steps:
      - name: Setup Fortran
        uses: gha3mi/setup-fortran-conda@latest
        with:
          compiler: ${{ matrix.compiler }}
          platform: ${{ matrix.os }}
          extra-packages: ${{ matrix.extra-packages }}

      - name: fpm test (release)
        run: fpm test --compiler ${{ matrix.compiler }} --profile release --verbose

#CMAKE#  # Run CMake + Ninja build/tests across OS/compiler matrix
#CMAKE#  test_cmake:
#CMAKE#    name: ${{ matrix.os }}_${{ matrix.compiler }}_cmake
#CMAKE#    runs-on: ${{ matrix.os }}
#CMAKE#    strategy:
#CMAKE#      fail-fast: false
#CMAKE#      matrix:
#CMAKE#        os: [ubuntu-latest, macos-latest, windows-latest]
#CMAKE#        compiler: [gfortran, ifx, lfortran, flang-new, nvfortran]
#CMAKE#        include:
#CMAKE#          - os: ubuntu-latest
#CMAKE#            extra-packages: ""
#CMAKE#          - os: windows-latest
#CMAKE#            extra-packages: ""
#CMAKE#          - os: macos-latest
#CMAKE#            extra-packages: ""
#CMAKE#        exclude:
#CMAKE#          - os: macos-latest
#CMAKE#            compiler: flang-new
#CMAKE#          - os: macos-latest
#CMAKE#            compiler: ifx
#CMAKE#          - os: macos-latest
#CMAKE#            compiler: nvfortran
#CMAKE#          - os: windows-latest
#CMAKE#            compiler: nvfortran
#CMAKE#
#CMAKE#    steps:
#CMAKE#      - name: Setup Fortran
#CMAKE#        uses: gha3mi/setup-fortran-conda@latest
#CMAKE#        with:
#CMAKE#          compiler: ${{ matrix.compiler }}
#CMAKE#          platform: ${{ matrix.os }}
#CMAKE#          extra-packages: ${{ matrix.extra-packages }}
#CMAKE#
#CMAKE#      - name: cmake test (release)
#CMAKE#        run: |
#CMAKE#          cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release -DCMAKE_Fortran_COMPILER=${{ matrix.compiler }} -G Ninja
#CMAKE#          cmake --build build/release
#CMAKE#          ctest --test-dir build/release --output-on-failure

  # Run Fortran linter with Fortitude
  linter_fortitude:
    name: Run Fortitude Linter
    runs-on: ubuntu-latest
    steps:
      - name: Run Fortitude Linter
        uses: gha3mi/setup-fortran-conda@latest
        with:
          fortitude-check: true
          fortitude-settings: "--output-format github"
